version: "2"

run:
  timeout: 5m
  build-tags:
    - intgration
    - testing
    - pact
    - functional
  modules-download-mode: readonly
  concurrency: 4
  relative-path-mode: gomod

linters:
  default: none
  enable:
    - bodyclose
    - revive
    - staticcheck
    - unconvert
    - gocritic
    - ireturn
    - misspell
    - sloglint
    - ineffassign
    - unused
    - errname
    # - errcheck
    # - depgaurd
    # - errchkjson
  settings:
    staticcheck:
      checks:
        # Below is the default set
        - "all"
        - "-ST1000"
        - "-ST1003"
        - "-ST1016"
        - "-ST1020"
        - "-ST1021"
        - "-ST1022"

        ##### TODO: fix and enable these
        # 4 occurrences.
        # Use fmt.Fprintf(x, ...) instead of x.Write(fmt.Sprintf(...)) https://staticcheck.dev/docs/checks#QF1012
        - "-QF1012"
        # 6 occurrences.
        # Apply De Morgan’s law https://staticcheck.dev/docs/checks#QF1001
        - "-QF1001"
        # 10 occurrences.
        # Convert if/else-if chain to tagged switch https://staticcheck.dev/docs/checks#QF1003
        - "-QF1003"

        ##### These have been vetted to be disabled.
        # 55 occurrences. Omit embedded fields from selector expression https://staticcheck.dev/docs/checks#QF1008
        # Usefulness is questionable.
        - "-QF1008"

    revive:
      enable-all-rules: true
      rules:
        ##### P0: we should do it ASAP.
        - name: max-control-nesting
          # 10 occurences (at default 5). Deep nesting hurts readibility.
          arguments: [7]

        ##### P1: consider making a dent on these, but not critical.
        - name: argument-limit
          # 4 occurrences (at default 8). Long windy arguments list for functions are hard to read. Use structs instead.
          arguments: [12]
        - name: function-result-limit
          # 12 occurrences (at default 3). A function returning many results is probably too big.
          arguments: [7]
        - name: function-length
          # 155 occurrences (at default 0, 75). Really long functions should really be broken up in most cases.
          arguments: [0, 400]
        - name: cyclomatic
          # 204 occurrences (at default 10)
          arguments: [100]
        - name: cognitive-complexity
          arguments: [197]
          # 441 occurrences (at default 7). We should try to lower it (involves significant refactoring).

        ##### P2: nice to have.
        - name: max-public-structs
          # 7 occurrences (at default 5). Might indicate overcrowding of public API.
          arguments: [21]

        ###### Permanently disabled. Below have been reviewed and vetted to be unnecessary.
        - name: line-length-limit
          # Formatter `golines` takes care of this.
          disabled: true
        - name: nested-structs
          # 5 occurrences. Trivial. This is not that hard to read.
          disabled: true
        - name: flag-parameter
          # 52 occurrences. Not sure if this is valuable.
          disabled: true
        - name: unused-parameter
          # 505 occurrences. A lot of work for a marginal improvement.
          disabled: true
        - name: unused-receiver
          # 31 occurrences. Ibid.
          disabled: true
        - name: add-constant
          # 2605 occurrences. Kind of useful in itself, but unacceptable amount of effort to fix
          disabled: true
        - name: exported
          disabled: true
        - name: confusing-naming
          disabled: true

formatters:
  enable:
    - gci
    - golines
    - gofumpt
  settings:
    gci:
      sections:
        - standard
        - default
        - blank
        - dot
        - alias
        - localmodule
      custom-order: true
      no-lex-order: false
    golines:
      max-len: 100
      tab-len: 4
      shorten-comments: true
      chain-split-dots: true
  exclusions:
    generated: strict

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

output:
  show-stats: false
