# Options for analysis running.
run:
  timeout: 5m
  issues-exit-code: 2
  tests: true
  build-tags:
    - intgration
    - testing
    - pact
    - functional
  allow-parallel-runners: true
  allow-serial-runners: true
  modules-download-mode: readonly

linters:
  disable-all: true
  fast: true
  enable:
    - bodyclose
    - staticcheck
    - errcheck
    - canonicalheader
    - errchkjson
    - revive
    - ireturn
    - misspell
    - gci
    - lll
    - sloglint
    - ineffassign
    - unused
    - errname

linters-settings:
  gci:
    sections:
      - standard
      - default
      - blank
      - dot
      - alias
      - localmodule
    skip-generated: true
    custom-order: true
    no-lex-order: false
  lll:
    line-length: 80
    tab-width: 4

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - lll
    - path: _mock\.go
        - bodyclose
        - staticcheck
        - errcheck
        - canonicalheader
        - errchkjson
        - revive
        - ireturn
        - misspell
        - gci
        - lll
        - sloglint
        - ineffassign
        - unused
