version = 3
[plugins."io.containerd.cri.v1.runtime".containerd]
	default_runtime_name = "crun"
	[plugins."io.containerd.cri.v1.runtime".containerd.runtimes]
		[plugins."io.containerd.cri.v1.runtime".containerd.runtimes.crun]
			runtime_type = "io.containerd.runc.v2"
			[plugins."io.containerd.cri.v1.runtime".containerd.runtimes.crun.options]
				BinaryName = "/usr/bin/crun"
				SystemdCgroup = true
[plugins.'io.containerd.cri.v1.images']
	snapshotter = "overlayfs"
	use_local_image_pull = true
	max_concurrent_downloads = 5
